name: dice
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - images/dice_1.png
   - images/dice_2.png
   - images/dice_3.png
   - images/dice_4.png
   - images/dice_5.png
   - images/dice_6.png

